function(test)
  #set(str "abcdefg hello")
  #string_totitle(${str})
  #ans(res)
  #assert("${res}" STREQUAL "Abcdefg Hello")

  #set(res "")
  #set(str "a abcdefg hello")
  #string_totitle(${str})
  #ans(res)
  #assert("${res}" STREQUAL "A Abcdefg Hello")

  #set(res "")
  #set(str "a abcdefg hello superTrump?")
  #string_totitle(${str})
  #ans(res)
  #assert("${res}" STREQUAL "A Abcdefg Hello superTrump?")

  #set(res "")
  set(str "!a abcdefg hello superTrump?")
  string_totitle(${str})
  ans(res)
  assert("${res}" STREQUAL "!A Abcdefg Hello superTrump?")
endfunction()