# transforms the specified string to title case
function(string_totitle str)
  set(small a an and as at but by en for if in of on or the to via vs v v. vs. A An And As At But By En For If In Of On Or The To Via Vs V V. Vs.)
  set(other "[^ ]+")
  set(ws "[ ]+")
  set(is_subsentence true)

  string_encode_list(${str})
  ans(str_encoded)
  string(REGEX MATCHALL "(${ws})|(${other})" tokens "${str_encoded}")
  
  while(true)
    list(LENGTH tokens length)
    if(NOT length)
      break()
    endif()
    list(GET tokens 0 token)
    list(REMOVE_AT tokens 0)

   #message("Looking at=${token}")
    if("${token}" MATCHES "^([^a-zA-Z0-9]*)([a-zA-Z])([a-z]*)([:?!']*)$")
     #message("Matched=${token}")
      set(pre ${CMAKE_MATCH_1})
      set(first_letter ${CMAKE_MATCH_2})
      set(lc_letters ${CMAKE_MATCH_3})
      set(post ${CMAKE_MATCH_4})
      
      list(FIND small "${first_letter}${lc_letters}" index)
      if(index GREATER -1)
       #message("Found small=${token}")
        if(is_subsentence)
         #message("To upper small=${token}")
          string(TOUPPER ${first_letter} first_letter)
        else()
         #message("To lower small=${token}")
          string(TOLOWER ${first_letter} first_letter)
        endif()
        set(token "${pre}${first_letter}${uc_letters}${lc_letters}${post}")
      elseif(NOT uc_letters)
       #message("Make upper case=${token}")
        string(TOUPPER ${first_letter} first_letter)
        set(token "${pre}${first_letter}${uc_letters}${lc_letters}${post}")
      endif()
      
      #message("post=${post}")
      if(NOT post)
       #message("Subsentence disabled")
        set(is_subsentence false)
      else()
       #message("Subsentence enabled")
        set(is_subsentence true)
      endif()
    endif()

    set(res "${res}${token}")
  endwhile()

  return_ref(res)
endfunction()